version: 0.1.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  nodejs_version: 8
install:
- ps: Install-Product node $env:nodejs_version
- git submodule update --init --recursive
- cmd: >-
    cd src\dserfozo-rpcbindings

    npm install

    npm run build

    cd ..\..


    cd tests\DSerfozo.RpcBindings.Node.IntegrationTests

    npm install

    cd ..\..


    dotnet restore
build_script:
- cmd: msbuild DSerfozo.RpcBindings.sln /t:Build /p:Configuration=Release /p:BuildNumber=%APPVEYOR_BUILD_NUMBER%
test_script:
- cmd: 'cd src\dserfozo-rpcbindings && npm run test'
- cmd: '%xunit20%\xunit.console.x86 tests\DSerfozo.RpcBindings.Tests\bin\Release\net461\DSerfozo.RpcBindings.Tests.dll'  
- cmd: '%xunit20%\xunit.console.x86 tests\DSerfozo.RpcBindings.Json.Tests\bin\Release\net461\DSerfozo.RpcBindings.Json.Tests.dll'
- cmd: '%xunit20%\xunit.console.x86 tests\DSerfozo.RpcBindings.Node.IntegrationTests\bin\Release\net461\DSerfozo.RpcBindings.Node.IntegrationTests.dll'