version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  nodejs_version: 8
install:
- ps: Install-Product node $env:nodejs_version
- git submodule update --init --recursive
- cmd: >-
    cd src\dserfozo-rpcbindings

    npm install

    npm run build

    cd ..\..


    cd tests\DSerfozo.RpcBindings.Node.IntegrationTests

    npm install

    cd ..\..


    dotnet restore
build:
  project: DSerfozo.RpcBindings.sln
  verbosity: minimal
test_script:
- cmd: '%xunit20%\xunit.console.x86 tests\DSerfozo.RpcBindings.Tests\bin\Release\net461\DSerfozo.RpcBindings.Tests.dll'  