version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  nodejs_version: 8
install:
- ps: Install-Product node $env:nodejs_version
- git submodule update --init --recursive
- cmd: >-
    pushd src\dserfozo-rpcbindings

    npm install

    npm run build

    popd


    pushd tests\DSerfozo.RpcBindings.Node.IntegrationTests

    npm install

    popd


    dotnet restore
build:
  project: DSerfozo.RpcBindings.sln
  verbosity: minimal