version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  nodejs_version: 8
install:
- ps: Install-Product node $env:nodejs_version
- cmd: git submodule update --init --recursive
- cmd: dotnet restore
build:
  project: DSerfozo.RpcBindings.sln
  verbosity: minimal
test_script:
- cmd: 'cd src\dserfozo-rpcbindings && npm run test'
- cmd: '%xunit20%\xunit.console.x86 tests\DSerfozo.RpcBindings.Tests\bin\Release\net461\DSerfozo.RpcBindings.Tests.dll'  
- cmd: '%xunit20%\xunit.console.x86 tests\DSerfozo.RpcBindings.Json.Tests\bin\Release\net461\DSerfozo.RpcBindings.Json.Tests.dll'
- cmd: '%xunit20%\xunit.console.x86 tests\DSerfozo.RpcBindings.Node.IntegrationTests\bin\Release\net461\DSerfozo.RpcBindings.Node.IntegrationTests.dll'